import Head from 'next/head'
import Header from '../components/common/Header/Header'
import HomePage from '../components/pages/HomePage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bilal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/b2.svg" />
      </Head>
      <Header />
      <HomePage />
    </div>
  )
}
