import Head from 'next/head';
import Footer from '../components/common/Footer/Footer';
import Header from '../components/common/Header/Header';
import StudentsWorkPage from '../components/pages/StudentsWorkPage';

export default function Studentsworks() {
  return (
    <div>
      <Head>
        <title>Работы студентов</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/b2.png" />
      </Head>
      <Header />
      <StudentsWorkPage />
      <Footer />
    </div>
  );
}
